name: 05 - 2 - Event Filters and Activity Types

on:
  # if activity type is not specified, it will opened, reopened, or synchronized by default
  pull_request:
    types:
      - closed
    branches:
      - main

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is closed"