name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITE_VAR: "workflow"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITE_VAR: "job"
    steps:
      - name: Display information
        run: |
          echo "The event name is ${{ github.event_name }}"
          echo "The branch is ${{ github.ref }}"
          echo "The commit SHA is ${{ github.sha }}"
          echo "The actor is ${{ github.actor }}"
          echo "The workflow name is ${{ github.workflow }}"
          echo "The job run ID is ${{ github.run_id }}"
          echo "The job run number is ${{ github.run_number }}"
      - name: Retrieve Variable
        run: echo "Variable is ${{ vars.MY_VAR }}"
      - name: Print Env Variables with declared step env
        env:
          MY_OVERWRITE_VAR: "step"
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Job env: ${{ env.MY_JOB_VAR }}"
          echo "Overwrite env: ${{ env.MY_OVERWRITE_VAR }}"
      - name: Print Env Variables without declaring step env
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Job env: ${{ env.MY_JOB_VAR }}"
          echo "Overwrite env: ${{ env.MY_OVERWRITE_VAR }}"
  echo-data2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Variables with declared step env
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR"
          echo "Overwrite env: $MY_OVERWRITE_VAR"
