name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print startup'
        if: ${{inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "The branch is ${{ github.ref }}"
          echo "The commit SHA is ${{ github.sha }}"
          echo "Runner OS": ${{ runner.os }}
      - name: '[debug] Print when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "Triggered from main branch"
      - name: Greeting
        run: echo 'Hello, world!'
