name: 08 - Using Variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "workflow var"
  OVERWRITE_VAR: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "job var"
      OVERWRITE_VAR: "I have been overwritten at the job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "step var"
          step_var2: "step var2"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: $step_var2"
          echo "Job env: ${{ env.JOB_VAR }}"
          echo "Workflow env: ${{ env.WORKFLOW_VAR }}"
          echo "Overwrite env: ${{ env.OVERWRITE_VAR }}"
      - name: Overwrite job variable
        env:
          OVERWRITE_VAR: "I have been overwritten at the step level"
        run: |
          echo "Overwrite env: ${{ env.OVERWRITE_VAR }}"